# The routes of the project.
#
# Each route describes how an incoming URL is going
# to be processed by Platform.sh.

"https://php.{default}/":
    type: upstream
    upstream: "php:http"

"https://nodejs.{default}/":
    type: upstream
    upstream: "nodejs:http"

