# The routes of the project.
#
# Each route describes how an incoming URL is going
# to be processed by Platform.sh.

"https://relationships.{default}/":
    type: upstream
    upstream: "relationships:http"
    cache:
        enabled: true
        cookies: []
        default_ttl: 300

"https://php.{default}/":
    type: upstream
    upstream: "php:http"

"https://nodejs.{default}/":
    type: upstream
    upstream: "nodejs:http"

