# This file defines services you want available to your application.

elasticsearch77:
    type: elasticsearch:7.7
    disk: 256
    size: S
influxdb18:
    type: influxdb:1.8
    disk: 256
    size: S
kafka25:
    type: kafka:2.5
    disk: 512
    size: S
memcached16:
    type: memcached:1.6
    size: S
mongodb36:
    type: mongodb:3.6
    disk: 1024
    size: S
mariadb104:
    type: mariadb:10.4
    disk: 256
    size: S
postgresql11:
    type: postgresql:11
    disk: 256
    size: S
rabbitmq38:
    type: rabbitmq:3.8
    disk: 1024
    size: S
redis6:
    type: redis:6.0
    size: S
solr80:
    type: solr:8.0
    disk: 256
    size: S
    configuration:
        cores:
            maincore:
                conf_dir: !archive "solr-config"
        endpoints:
            solr:
                core: maincore
